### ISSUE TITLE
Handle TVC commands

### ISSUE THREAD

**Issue by ofacklam** [EPFLRocketTeam/BellaLui#11]
Handle all the different commands including:
- boot
- shutdown
- ...

**Comment by AlbericDeLajarte** [comment]
Shutdown pourrait être pratique, mais n'est pas critiques en tout cas. Boot est déjà implémenté

**Comment by ofacklam** [comment]
Dans mes souvenirs il y avait d'autres commandes intéressantes aussi, mais j'ai plus les détails en tête. Pour la calibration notamment, tout est OK de ton coté ?

**Comment by AlbericDeLajarte** [comment]
normalement c'est bon. Je te redis après nos tests

**Comment by ofacklam** [comment]
Finalement il y a besoin d'autres choses que Boot & Shutdown ? :)

**Comment by iac26** [comment]
Ca c'est les commandes qu'il faudrait implémenter:
	TVC_COMMAND_NO_OPERATION = 0x00,
	TVC_COMMAND_BOOT = 0x01,
	TVC_COMMAND_SHUTDOWN = 0x02,
	TVC_COMMAND_ABORT = 0x03,
	TVC_COMMAND_RECOVER = 0x04
AV devrait juste forward la commande que GS génère.
